repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
    - id: markdownlint
      files: \.(md|mdown|markdown)$

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.6.0
    hooks:
      - id: cspell
        files: \.(md|mdown|markdown)$

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=88]
