site_name: AIGA Template
site_description: A documentation site for the AIGA Template

theme:
  name: material
  features:
    - navigation.instant
    - content.tabs.link
    - content.code.copy

nav:
  - Home: 'README.md'
  - Design:
    - Reference Architecture: design/reference-architecture.md
    - Template Components: design/template-components.md
    - Identity and Access: design/identity-and-access.md
    - Document Loading: design/document-loading.md
    - Accountability Report: design/accountability-report.md
    - GenAI Lifecycle: design/lifecycle.md
    - Success Criteria for Evaluation: design/model-evaluation-success-criteria.md
  - Decision Log: design/decision-log.md
  - Contributing:
    - Developer Guide: contributing/developer-guide.md
    - PromptFlow: contributing/promptflow.md
    - Backlog Traceability: contributing/backlog-integration-with-github.md
    - Branching Strategy: contributing/branching-strategy.md
  - Onboarding:
    - Adding Metrics: onboarding/adding-metrics.md
    - Getting Started: onboarding/getting-started.md
    - Running PromptFlow: onboarding/running-promptflow.md
    - Running with Docker: onboarding/running-with-docker.md
    - Running Evaluation locally: onboarding/experiment-evaluate-locally.md
    - Deployment: onboarding/deployment.md
    - GitHub:
      - GitHub Actions: onboarding/github-actions.md
      - GitHub Variables: onboarding/github-variables.md
      - GitHub Secrets: onboarding/github-secrets.md
    - Observability:
        - Observability: onboarding/observability.md
        - Alerting: onboarding/alerting.md
    - LLMOps:
        - LLMOps CI/CD: onboarding/llmops.md
        - Experiment YAML Structure Guide: onboarding/experiment-configuration-guide.md

copyright: "&copy; Microsoft"

markdown_extensions:

  # Python Markdown
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/commercial-software-engineering
