site_name: AIGA Template
site_description: A documentation site for the AIGA Template

theme:
  name: material
  features:
    - navigation.instant
    - content.tabs.link
    - content.code.copy

nav:
  - Home: 'README.md'
  - Architecture:
    - Reference Architecture: 'design/aiga-infrastructure.md'
    - Decision Log: Decision-Log.md
  - User Guides:
    - Developer Guide: developer-guide.md
    - Backlog traceability: Backlog-traceability.md
  - Onboarding:
    - Deployment: 'onboarding/deployment.md'
    - Observability: 'onboarding/observability.md'
    - Workflows: 'onboarding/workflows.md'

copyright: "&copy; GSK"

markdown_extensions:

  # Python Markdown
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gsk-tech
