site_name: AIGA Template
site_description: A documentation site for the AIGA Template

theme:
  name: material
  features:
    - navigation.instant
    - content.tabs.link
    - content.code.copy

nav:
  - Home: 'README.md'
  - Design:
    - Reference Architecture: design/reference-architecture.md
    - Decision Log: design/decision-log.md
  - User Guides:
    - Developer Guide: developer-guide.md
    - Backlog Traceability: backlog-integration-with-github.md
  - Onboarding:
    - Deployment: onboarding/deployment.md
    - GitHub Actions: onboarding/github-actions.md
    - Observability:
        - Alerting: onboarding/alerting.md

copyright: "&copy; GSK"

markdown_extensions:

  # Python Markdown
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gsk-tech
