name: setup-environment

description: Prepares build environment for python and prompt flow related workflow execution.

inputs:
  version_spec:
    description: "The Python version to use in the environment."
    default: "3.9"
    required: false

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install poetry
      shell: bash
      run: pip install poetry

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.version_spec }}
        cache: 'poetry'

    - name: Setup Environment
      shell: bash
      run: make setup
