services:
  promptflow:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - USE_CASE_BASE_PATH=promptflow
        - FLOW_NAME=inference
      platforms:
        - linux/amd64
    environment:
      - AOAI_API_BASE=${AOAI_API_BASE}
      - AOAI_API_KEY=${AOAI_API_KEY}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZ_SQL_DATABASE=${AZ_SQL_DATABASE}
      - AZ_SQL_SERVER=${AZ_SQL_SERVER}
    ports:
      - "8080:8080"
  docs:
    image: squidfunk/mkdocs-material
    ports:
      - "8090:8000"
    volumes:
      - ../:/docs
    command: [ "serve", "-a", "0.0.0.0:8000" ]
    profiles:
      - docs
