services:
  promptflow:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - USE_CASE_BASE_PATH=promptflow
        - FLOW_NAME=inference
      platforms:
        - linux/amd64
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZ_SQL_DATABASE=${AZ_SQL_DATABASE}
      - AZ_SQL_SERVER=${AZ_SQL_SERVER}
      - PING_FED_URL=${PING_FED_URL}
      - KGW_CLIENT_SECRET=${KGW_CLIENT_SECRET}
      - KGW_CLIENT_ID=${KGW_CLIENT_ID}
      - KGW_ENDPOINT=${KGW_ENDPOINT}
      - SEARCH_SERVICE_NAME=${SEARCH_SERVICE_NAME}
    ports:
      - "8080:8080"
  docs:
    image: squidfunk/mkdocs-material
    ports:
      - "8090:8000"
    volumes:
      - ../:/docs
    command: [ "serve", "-a", "0.0.0.0:8000" ]
    profiles:
      - docs
