name: execute-unit-tests

description: execute unit tests

runs:
  using: composite
  steps:
    - name: Build
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: make unittest

    - name: Publish Unit Test Results
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: "**/test-*.xml"
