name: deploy-webapp

description: deploys container on webapp

inputs:
  USE_CASE_BASE_PATH:
    description: "The path to the flow to be registered and deployed"
    required: true
  DEPLOY_ENVIRONMENT:
    description: "Env stage e.g. dev, test, prod"
    required: true
  REGISTRY_NAME:
    description: "Container registry endpoint"
    required: true
  REGISTRY_SECRET:
    description: "Container registry secret"
    required: true
  WEBAPP_SUBSCRIPTION_ID:
    description: "Web application subscription ID"
    required: true
  WEBAPP_RG_NAME:
    description: "Web application resource group name"
    required: true
  WEBAPP_NAME:
    description: "Web application name"
    required: true

runs:
  using: composite
  steps:
    - name: deploy docker image to registry
      shell: bash
      run: REGISTRY_NAME=${{ inputs.REGISTRY_NAME }} REGISTRY_SECRET=${{ inputs.REGISTRY_SECRET }} USE_CASE_BASE_PATH=${{ inputs.USE_CASE_BASE_PATH }} DEPLOY_ENVIRONMENT=${{ inputs.DEPLOY_ENVIRONMENT }} build_id=${{ github.run_id }} ./llmops/common/scripts/gen_docker_image.sh

    - name: deploy webapp
      shell: bash
      run: build_id=${{ github.run_id }} REGISTRY_NAME=${{ inputs.REGISTRY_NAME }} WEBAPP_SUBSCRIPTION_ID=${{ inputs.WEBAPP_SUBSCRIPTION_ID }} WEBAPP_RG_NAME=${{ inputs.WEBAPP_RG_NAME }} WEBAPP_NAME=${{ inputs.WEBAPP_NAME }} USE_CASE_BASE_PATH=${{ inputs.USE_CASE_BASE_PATH }} DEPLOY_ENVIRONMENT=${{ inputs.DEPLOY_ENVIRONMENT }} ./llmops/common/scripts/az_webapp_deploy.sh
