name: deploy-webapp

description: deploys container on webapp

inputs:
  USE_CASE_BASE_PATH:
    description: "The path to the flow to be registered and deployed"
    required: true
  DEPLOY_ENVIRONMENT:
    description: "Env stage e.g. dev, test, prod"
    required: true
  REGISTRY_NAME:
    description: "Container registry endpoint"
    required: true
  REGISTRY_SECRET:
    description: "Container registry secret"
    required: true
  WEBAPP_SUBSCRIPTION_ID:
    description: "Web application subscription ID"
    required: true
  WEBAPP_RG_NAME:
    description: "Web application resource group name"
    required: true
  WEBAPP_NAME:
    description: "Web application name"
    required: true

runs:
  using: composite
  steps:
    - name: login to ACR
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.REGISTRY_NAME }}.azurecr.io
        username: ${{ inputs.REGISTRY_NAME }}
        password: ${{ inputs.REGISTRY_SECRET }}

    - name: build docker image
      shell: bash
      run: |
        CONFIG_PATH="./$USE_CASE_BASE_PATH/experiment.yaml"
        REGISTRY_ENDPOINT="$REGISTRY_NAME.azurecr.io"
        FLOW_NAME=$(yq '.flow' "$CONFIG_PATH" |  sed 's/"//g')
        IMAGE_NAME="$REGISTRY_ENDPOINT"/"$USE_CASE_BASE_PATH"/"$FLOW_NAME"_"$DEPLOY_ENVIRONMENT"

        cd docker
        docker compose build --build-arg USE_CASE_BASE_PATH="$USE_CASE_BASE_PATH" --build-arg FLOW_NAME="$FLOW_NAME" promptflow

        docker tag docker-promptflow "$IMAGE_NAME":"$BUILD_ID"
        docker tag docker-promptflow "$IMAGE_NAME":"latest"

        docker push "$IMAGE_NAME":"$BUILD_ID"
        docker push "$IMAGE_NAME":"latest"
      env:
        USE_CASE_BASE_PATH: ${{ inputs.USE_CASE_BASE_PATH }}
        REGISTRY_NAME: ${{ inputs.REGISTRY_NAME }}
        DEPLOY_ENVIRONMENT: ${{ inputs.DEPLOY_ENVIRONMENT }}
        BUILD_ID: ${{ github.run_id }}

    - name: deploy webapp
      shell: bash
      run: build_id=${{ github.run_id }} REGISTRY_NAME=${{ inputs.REGISTRY_NAME }} WEBAPP_SUBSCRIPTION_ID=${{ inputs.WEBAPP_SUBSCRIPTION_ID }} WEBAPP_RG_NAME=${{ inputs.WEBAPP_RG_NAME }} WEBAPP_NAME=${{ inputs.WEBAPP_NAME }} USE_CASE_BASE_PATH=${{ inputs.USE_CASE_BASE_PATH }} DEPLOY_ENVIRONMENT=${{ inputs.DEPLOY_ENVIRONMENT }} ./llmops/common/scripts/az_webapp_deploy.sh
