name: build_validation

on:
  workflow_call:
    inputs:
      use_case_base_path:
        type: string
        description: "The flow use-case to validate"
        required: true
    secrets:
      azure_credentials:
        description: "service principal auth to Azure"
        required: true

jobs:
  validate-code:
    name: job for validating code and structure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4

      - name: Configure Azure ML Agent
        uses: ./.github/actions/configure_azureml_agent
        with:
          base_path: ${{ inputs.use_case_base_path }}

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: load the current Azure subscription details
        id: subscription_details
        shell: bash
        run: |
          export subscriptionId=$(az account show --query id -o tsv)
          echo "SUBSCRIPTION_ID=$subscriptionId" >> $GITHUB_OUTPUT

      - name: Python code linting
        run: poetry run flake8 ./llmops

      - name: Execute Unit Tests
        shell: bash
        run: |
          poetry run pytest ./promptflow/chat_with_pdf/tests --junitxml=junit/test-results.xml --cov=. --cov-report=xml

      - name: Publish Unit Test Results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: "**/test-*.xml"
