name: chat_with_pdf_pr_dev_workflow

on:
  workflow_call:
    inputs:
      env_name:
        type: string
        description: "Execution Environment"
        required: true
        default: "dev"
      use_case_base_path:
        type: string
        description: "The flow use case to execute"
        required: true
        default: "promptflow/chat_with_pdf"
  pull_request:
    branches:
      - main
    paths:
      - 'promptflow/chat_with_pdf/**'
      - '.github/**'
      - 'llmops/**'

#=====================================
# Execute platform_pr_dev_workflow workflow for experiment, evaluation and deployment of flows
#=====================================
jobs:
  execute-platform-pr-workflow:
    uses: ./.github/workflows/platform_pr_dev_workflow.yml
    with:
      env_name: ${{ inputs.env_name || 'dev'}}
      use_case_base_path: ${{ inputs.use_case_base_path || 'promptflow/chat_with_pdf' }}
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      aoai_api_key: ${{ secrets.AOAI_API_KEY }}
      aoai_api_base: ${{ secrets.AOAI_API_BASE }}
