name: ci-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development
      - virginie/test/chatwithpdf

permissions:
  contents: read
  packages: write

#=====================================
# Execute run-workflow for experiment and evaluate-workflow for the evaluation
#=====================================
jobs:
  devcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build image for DevContainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/gsk-tech/aiga
          cacheFrom: ghcr.io/gsk-tech/aiga
          push: always

  run-workflow:
    uses: ./.github/workflows/run-workflow.yml
    with:
      env_name: ${{ vars.TMP_ENV }}
      use_case_base_path: ${{ vars.PROMPTFLOW_BASE_PATH }}
    secrets: inherit

  evaluate-workflow:
    needs: run-workflow
    uses: ./.github/workflows/evaluate-workflow.yml
    with:
      env_name: ${{ vars.TMP_ENV }}
      use_case_base_path: ${{ vars.PROMPTFLOW_BASE_PATH }}
      deployment_type: ${{ vars.DEPLOYMENT_TARGET }}
    secrets: inherit