name: ci-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development

permissions:
  contents: read
  packages: write

#=====================================
# Execute run-workflow for experiment and evaluate-workflow for the evaluation
#=====================================
jobs:
  devcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build image for DevContainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/gsk-tech/aiga
          cacheFrom: ghcr.io/gsk-tech/aiga
          push: always

  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Set up Python Env
        uses: ./.github/actions/setup-environment
      - run: poetry run mkdocs gh-deploy --force

  run-workflow:
    uses: ./.github/workflows/run-workflow.yml
    secrets: inherit

  evaluate-workflow:
    needs: run-workflow
    uses: ./.github/workflows/evaluate-workflow.yml
    secrets: inherit
