name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - run: pip install poetry
      - run: make setup

      - name: Run pre-commit checks
        run: make pre-commit