name: promptflow-cd-workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to run the workflow with (playground, dev, uat, prod)"
        required: false

permissions:
  contents: read
  packages: write

jobs:
  setup-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
      - id: setup
        name: Set up Environment variable
        uses: ./.github/actions/environment-variable
        with:
          environment:  ${{ inputs.environment }}
          default_environment: ${{ vars.DEFAULT_ENVIRONMENT }}
    outputs:
      environment: ${{ steps.setup.outputs.environment }}

  deploy:
    name: prompt flow deployment job
    needs: setup-env
    uses: ./.github/workflows/reusable-cd-workflow.yml
    secrets: inherit
    with:
      environment: ${{ needs.setup-env.outputs.environment }}
      checkout_sha_ref: ${{ github.sha }}
