name: promptflow-ci-workflow

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - development

permissions:
  contents: read
  packages: write

#=====================================
# Execute run-workflow for experiment and evaluate-workflow for the evaluation
#=====================================
jobs:
  devcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build image for DevContainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/gsk-tech/aiga
          cacheFrom: ghcr.io/gsk-tech/aiga
          push: always

  run-workflow:
    uses: ./.github/workflows/run-workflow.yml
    secrets: inherit

  evaluate-workflow:
    needs: run-workflow
    uses: ./.github/workflows/evaluate-workflow.yml
    secrets: inherit

  validate-docker:
    uses: ./.github/workflows/validate-docker.yml
    secrets: inherit
    with:
      compose_folder: "docker"
      validation_url: "http://localhost:8080/health"