name: run-workflow

on:
  workflow_call:
    secrets:
      AZURE_CREDENTIALS:
        description: "service principal auth to Azure"
        required: true

jobs:
  run-workflow:
    name: prompt flow bulk run
    runs-on: ubuntu-latest
    environment: ${{ vars.TMP_ENV }}

    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2.1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Load Secrets from Azure Key Vault
        uses: ./.github/actions/load-secrets
        with:
          azureKeyVaultName: ${{ vars.KEY_VAULT_NAME }}

      - name: Set up Python Env
        uses: ./.github/actions/setup-environment

      #=====================================
      # Registers experiment dataset in Azure ML as Data Asset
      # Reads appropriate field values from experiment.yaml or experiment.<env>.yaml
      #=====================================
      - name: Register experiment data asset
        uses: ./.github/actions/execute-script
        with:
          step_name: "Register experiment data asset"
          script_parameter: |
            python -m llmops.common.register_data_asset \
            --subscription_id ${{ env.AZURE_SUBSCRIPTION_ID }} \
            --base_path ${{ vars.PROMPTFLOW_BASE_PATH }} \
            --env_name ${{ vars.TMP_ENV }}

      #=====================================
      # Executes Standard flow for a scenario
      # Generates Reports for each RUN as well as consolidated one
      # Execute a RUN for each unique variant combination (keeping default variant id for other nodes)
      # Loads appropriate experiment data from Azure ML data asset
      # Reads appropriate field values from experiment.yaml or experiment.<env>.yaml
      # Prompt Flow connections should pre-exist
      # used automatic (serverless) runtime by default
      #=====================================
      - name: Promptflow E2E Test
        uses: ./.github/actions/execute-script
        with:
          step_name: "Execute prompt flow bulk run"
          script_parameter: |
            python -m llmops.common.prompt_pipeline \
            --subscription_id ${{ env.AZURE_SUBSCRIPTION_ID }} \
            --build_id ${{ github.run_id }} \
            --base_path ${{ vars.PROMPTFLOW_BASE_PATH }} \
            --env_name ${{ vars.TMP_ENV }} \
            --output_file run_id.txt

      - name: Upload run_id.txt artifact
        uses: actions/upload-artifact@v4
        with:
         name: run-id-artifact
         path: run_id.txt
