name: Template Build Verification

on:
  workflow_call: null

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: make ci-build
