name: Template CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'

jobs:
  build_verification:
    name: Build Verification
    uses: ./.github/workflows/template-build-verification.yaml
    secrets: inherit
