name: Template Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Pre-Commit
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: make pre-commit

  build_verification:
    name: Build Verification
    uses: ./.github/workflows/template-build-verification.yaml
    secrets: inherit
