name: run_unit_tests

on:
  pull_request:
    branches:
      - main
      - development
    paths:
      - '.github/**'
      - 'llmops/**'
      - 'tests/**'


jobs:
  validate-code:
    name: job for validating code and structure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4

      - name: Configure Azure ML Agent
        uses: ./.github/actions/configure_azureml_agent
        with:
          base_path: ${{ inputs.use_case_base_path }}

      - name: Execute Common Unit Tests
        shell: bash
        run: |
          poetry run pytest ./promptflow/chat_with_pdf/tests --junitxml=junit/test-results.xml --cov=. --cov-report=xml

      - name: Publish Unit Test Results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: "**/test-*.xml"
