name: run_unit_tests

on:
  pull_request:
    branches:
      - main
      - development
    paths:
      - '.github/**'
      - 'llmops/**'
      - 'tests/**'


jobs:
  validate-code:
    name: job for validating code and structure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Load all build validation related dependencies
        shell: bash
        run: |
          set -e # fail on error
          pip install --upgrade pip
          pip install poetry
          make setup
          az version

      - name: Execute Common Unit Tests
        shell: bash
        run: |
          poetry run pytest ./promptflow/chat_with_pdf/tests --junitxml=junit/test-results.xml --cov=. --cov-report=xml

      - name: Publish Unit Test Results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: "**/test-*.xml"
